Create 2021-07-15-terzo-capitolo-wip.md
italia/developers.italia.it pull request #1035
Opened 2021-07-15 09:35 UTC by ruphy

## Description

This PR tackles:

* ...
* ...
* ...

In particular, the ...

## Checklist

* [ ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Ready for review! :rocket:

## Fixes

Fixes #

2021-07-15 09:35 UTC, developers-italia-droid commented
<!--
  1 failure:  There is a proble...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> Create 2021-07-15-terzo-capitolo-wip.md
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bc278fc09f5dda56cd9eb4af134e3aec13952d9a
</p>

2021-07-15 18:29 UTC, bfabio requested changes

2021-07-15 18:29 UTC, bfabio commented on _posts/it/2021-07-15-guida-sviluppo-gestione-software-libero-terzo-capitolo-politici.md
> +tags: Developers Opensource Guide PA consultazione
```suggestion
tags: developers opensource guide pa consultazione
```

2021-07-16 08:23 UTC, bfabio approved these changes

2021-07-16 08:24 UTC, merged