Add Italian news
italia/developers.italia.it pull request #1065
Opened 2021-09-29 11:27 UTC by ruphy

## Description

This PR tackles:

* ...
* ...
* ...

In particular, the ...

## Checklist

* [ ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Ready for review! :rocket:

## Fixes

Fixes #

2021-09-29 11:28 UTC, developers-italia-droid commented
<!--
  1 failure:  There is a proble...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> Add Italian news
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cb4d00493fa8ce5d8b5ced047807e1ce91b0561e
</p>

2021-09-29 18:42 UTC, bfabio requested changes

2021-09-29 18:42 UTC, bfabio commented on _posts/it/2021-09-29-developers-italia-pioniera-europa-competitiva.md
> +tags: developers opensource UE
```suggestion
tags: developers opensource ue
```

2021-09-30 08:01 UTC, libremente approved these changes

2021-09-30 08:16 UTC, bfabio approved these changes

2021-09-30 08:21 UTC, merged