Create: feat 2021-11-3-Progettare servizi pubblici basati su API.md
italia/developers.italia.it pull request #1099
Opened 2021-11-03 14:51 UTC by Francescopog

## Description

This PR tackles:

* ...
* ...
* ...

In particular, the ...

## Checklist

* [ ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Ready for review! :rocket:

## Fixes

Fixes #

2021-11-03 14:53 UTC, developers-italia-droid commented
<!--
  1 failure:  There is a proble...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  There is a problem with the commit message
> Create: feat 2021-11-3-Progettare servizi pubblici basati su API.md
- type must be lower-case
- type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2fb98e35cd2efa7e651f9037954ab7cc105a4841
</p>

2021-11-03 15:45 UTC, bfabio requested changes
We should rename the file to `2021-11-03-progettare-servizi-pubblici-basati-su-api.md`.

2021-11-03 15:45 UTC, bfabio commented on _posts/it/2021-11-3-Progettare servizi pubblici basati su API
> +date: 2021-11-3 13:00:00 +0200
```suggestion
date: 2021-11-03 13:00:00 +0200
```

2021-11-03 15:45 UTC, bfabio commented on _posts/it/2021-11-3-Progettare servizi pubblici basati su API
> +tags: developers designers API
```suggestion
tags: developers designers api
```

2021-11-03 15:45 UTC, bfabio commented on _posts/it/2021-11-3-Progettare servizi pubblici basati su API
> +
```suggestion
```

2021-11-03 15:45 UTC, bfabio commented on _posts/it/2021-11-3-Progettare servizi pubblici basati su API
> +A seguire Walter Manni, Celestina Paglia (Dipartimento di Web Strategies, Research & Innovation dell’Azienda Promozione Turismo della Regione **Emilia-Romagna**) e Stefano Vena (Altrama s.rl) ci hann
```suggestion
A seguire Walter Manni, Celestina Paglia (Dipartimento di Web Strategies, Research & Innovation dell’Azienda Promozione Turismo della Regione **Emilia-Romagna**) e Stefano Vena (Altrama s.r.l.) ci hanno parlato della realizzazione del servizio di condivisione di informazioni contenuto nel **portale turistico della Regione** tramite API. Uno strumento che ha consentito di semplificare la gestione e il trasferimento delle informazioni ai vari punti di pubblicazione locali.
```

2021-11-04 08:37 UTC, Francescopog reviewed
changed title

2021-11-04 08:38 UTC, bfabio approved these changes

2021-11-04 11:28 UTC, merged