feat: Create 2022-02-17-Developers-Italia-ridisegnare-il-sistema
italia/developers.italia.it pull request #1146
Opened 2022-02-17 16:06 UTC by Francescopog

## Description

This PR tackles:

* ...
* ...
* ...

In particular, the ...

## Checklist

* [ ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Ready for review! :rocket:

## Fixes

Fixes #

2022-02-17 16:07 UTC, developers-italia-droid commented
<!--
  1 failure:  There is a proble...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> Create 2022-02-17-Developers-Italia-ridisegnare-il-sistema.md
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2eef437c73fcd83f71df2a5e61cc62b6685a607e
</p>

2022-02-18 07:10 UTC, bfabio requested changes

2022-02-18 07:34 UTC, bfabio commented on _posts/it/2022-02-17-Developers-Italia-ridisegnare-il-sistema.md
> +Tutto è cominciato con il [Team per la trasformazione digitale](https://teamdigitale.governo.it/), una vera e propria startup governativa fondata con l’obiettivo di [“creare il sistema operativo del
```suggestion
Tutto è cominciato con il [Team per la trasformazione digitale](https://teamdigitale.governo.it/), una vera e propria startup governativa fondata con l’obiettivo di [“creare il sistema operativo del Paese”](https://medium.com/team-per-la-trasformazione-digitale/nuovo-sistema-operativo-paese-competenze-tecnologiche-programmi-be0d71b3f84b). Sotto la guida dell’allora Commissario Straordinario per l’Agenda Digitale Diego Piacentini, il Team ha dato vita a Developers Italia e [Designers Italia](https://designers.italia.it/), aventi il compito di diffondere una cultura della progettazione  e della programmazione dei servizi pubblici digitali del Paese.
```

2022-02-18 10:39 UTC, bfabio approved these changes

2022-02-18 10:39 UTC, merged