feat: Create 2022-07-01-verso-europa-digitale-sovrana-autonoma.md
italia/developers.italia.it pull request #1258
Opened 2022-07-01 15:22 UTC by Francescopog

## Description
@bfabio  grazie

This PR tackles:

* ...
* ...
* ...

In particular, the ...

## Checklist

* [ ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Ready for review! :rocket:

## Fixes

Fixes #

2022-07-01 15:23 UTC, developers-italia-droid commented
<!--
  1 failure:  There is a proble...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> Create 2022-07-01-verso-europa-digitale-sovrana-autonoma.md
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c2c5ecc52eac581a061ebf0c6d78006533c68e3c
</p>

2022-07-01 16:24 UTC, bfabio requested changes

2022-07-01 16:24 UTC, bfabio commented on _posts/it/2022-07-01-verso-europa-digitale-sovrana-autonoma.md
> +date: 2022-06-29 14:00:00 +0200
```suggestion
date: 2022-07-01 18:00:00 +0200
```

2022-07-01 16:24 UTC, bfabio commented on _posts/it/2022-07-01-verso-europa-digitale-sovrana-autonoma.md
> +La Presidenza francese ha costituito il Gruppo di lavoro nel febbraio 2022 nell’ambito della conferenza [“Building Europe's Digital Sovereignty”](https://presidence-francaise.consilium.europa.eu/en/n
```suggestion
La Presidenza francese ha costituito il Gruppo di lavoro nel febbraio 2022 nell’ambito della conferenza [“Building Europe's Digital Sovereignty”](https://presidence-francaise.consilium.europa.eu/en/news/the-building-europe-s-digital-sovereignty-conference/), con il fine di creare un incubatore europeo sui digital commons, promuovere opportunità di finanziamento dedicate e fornire assistenza agli Stati Membri sulle tematiche connesse. L’iniziativa ha il fine ultimo di contribuire efficacemente allo sviluppo e **mettere a frutto il potenziale dei *digital commons* e dell’*open source***. Il Dipartimento per la trasformazione digitale porta l'esperienza di Developers Italia nel team italiano che ha lavorato al rapporto, composto dal Dipartimento per la trasformazione digitale, Ministero dello Sviluppo Economico e Ministero degli affari esteri e della cooperazione internazionale.
```

2022-07-01 16:24 UTC, bfabio commented on _posts/it/2022-07-01-verso-europa-digitale-sovrana-autonoma.md
> +- Partecipa alla discussione su [Forum Italia](https://forum.italia.it/t/benvenuti-nel-forum-di-developers-italia/8) o su [Slack](https://developersitalia.slack.com/ssb/redirect)
```suggestion
- Partecipa alla discussione su [Forum Italia](https://forum.italia.it/) o su [Slack](https://slack.developers.italia.it)
```

2022-07-04 09:52 UTC, bfabio approved these changes

2022-07-04 09:53 UTC, merged