English translation for the "IO app" page.
italia/developers.italia.it pull request #1259
Opened 2022-07-02 12:09 UTC by DevLBD

## Description

This commit translates the IO app page in English.

## Checklist

* [ x] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ x] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ x] Have you written new tests for your core changes, as applicable?
* [ x] Have you successfully ran tests with your changes locally?
* [ x] Ready for review! :rocket:

## Fixes

Fixes #1212

2022-07-02 12:10 UTC, developers-italia-droid commented
<!--
  2 failure:  There is a proble..., There is a proble...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  There is a problem with the commit message
> Fix: #1212

Translated io.md
- type must be lower-case
- type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>There is a problem with the commit message
> Begin work on translation.

Created file to begin work on the translation.
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1ba9f81e3b343c680c3617b9ae8454bb085177f4
</p>

2022-07-06 16:30 UTC, bfabio requested changes

2022-07-06 16:30 UTC, bfabio commented on _platforms/en/io.md
> +lang: en
```suggestion
lang: en
ref:
  it: /it/io
```

We need this to link to the Italian page in the language switcher
(also, we need `en: /en/io` in the Italian page, to do the opposite)

2022-07-06 16:31 UTC, bfabio commented
@DevLBD thanks, and congrats for your first PR :rocket:

2022-07-06 19:55 UTC, DevLBD commented
> @DevLBD thanks, and congrats for your first PR 🚀

Thanks for your congratulations! I committed the changes you requested. Hope it is all looking good now!

Have a good day! 😃

2022-07-06 20:30 UTC, merged