feat: Create 2022-07-25-una-stagione-di-incontri-con-la-community
italia/developers.italia.it pull request #1285
Opened 2022-07-25 14:34 UTC by Francescopog

@bfabio

## Description

This PR tackles:

* ...
* ...
* ...

In particular, the ...

## Checklist

* [ ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Ready for review! :rocket:

## Fixes

Fixes #

2022-07-25 14:35 UTC, developers-italia-droid commented
<!--
  0 failure: 
  1 warning:  There is a proble...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>There is a problem with the commit message
> 2022-07-25-una-stagione-di-incontri-con-la-community.md

@bfabio
- subject may not be empty
- type may not be empty</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 35ea53bf57189ae6cffc932fd0fa5e36b59b2e89
</p>

2022-07-25 14:41 UTC, bfabio requested changes

2022-07-25 14:41 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +Altri mille di questi partecipanti! Si, perchè sono stati oltre mille le persone che hanno partecipato alla ricca stagione di eventi e occasioni di confronto organizzate da [Developers Italia](https:
```suggestion
Altri mille di questi partecipanti! Si, perché sono state oltre mille le persone che hanno partecipato alla ricca stagione di eventi e occasioni di confronto organizzate da [Developers Italia](https://developers.italia.it/) e [Designers Italia](https://designers.italia.it/). In nove puntate abbiamo discusso assieme di design system del Paese, di sviluppo aperto per i servizi pubblici, eGovernment Benchmark, ma anche di strumenti e risorse pratiche, come Git, Bootstrap Italia 2.0, UI Kit, progettazione di API REST e l’uso container.
```

2022-07-25 14:41 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +Tutto questo non sarebbe stato possibile senza la community di oltre 20.000 persone presenti sui canali [Forum Italia](https://forum.italia.it/) e [Slack Developers](https://slack.developers.italia.i
```suggestion
Tutto questo non sarebbe stato possibile senza la community di oltre 20.000 persone presenti sui canali [Forum Italia](https://forum.italia.it/) e [Slack Developers](https://slack.developers.italia.it/) composta da quanti si occupano di sviluppo, design, project management nelle PA, in house e aziende fornitrici. Un ringraziamento va quindi dedicato a loro, a chi ha partecipato agli eventi, ma anche a chi è intervenuto con un commento o un messaggio su Slack, a chi ha inviato una pull request su GitHub e a chi ha in qualche modo contribuito a far crescere a mantenere attiva questa comunità.
```

2022-07-25 14:41 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +- L’uso di Git ([23 febbraio](https://www.youtube.com/watch?v=2Ph4VSyi9lU&list=PLLZQsns4g-N5Eu8xv0L-iYhGU-IWBQSTL&index=9&t=2s))
```suggestion
- L’uso di Git ([23 febbraio](https://www.youtube.com/watch?v=2Ph4VSyi9lU&list=PLLZQsns4g-N5Eu8xv0L-iYhGU-IWBQSTL&index=9))
```

2022-07-25 14:41 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +COMMUNITY CALL
```suggestion
## Community call
```

2022-07-25 14:41 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +COMMUNITY LAB
```suggestion
## Community lab
```

2022-07-25 14:41 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +Durante queste occasioni abbiamo condiviso conoscenze, soluzioni e strumenti per migliorare i servizi pubblici digitali con i membri della community, favorendo l’incontro tra tecnici, designer, forni
```suggestion
Durante queste occasioni abbiamo condiviso conoscenze, soluzioni e strumenti per migliorare i servizi pubblici digitali con i membri della community, favorendo l’incontro tra tecnici, designer, fornitori e funzionari pubblici. In sostanza, tra tutti coloro che in qualche modo partecipano alla creazione e al mantenimento di servizi pubblici digitali.
```

2022-07-26 07:33 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +## Community call
```suggestion
#### Community call
```

2022-07-26 07:33 UTC, bfabio commented on _posts/it/2022-07-25-una-stagione-di-incontri-con-la-community.md
> +## Community lab
```suggestion
#### Community lab
```

2022-07-26 07:37 UTC, bfabio approved these changes

2022-07-26 07:42 UTC, merged