[#699] Updated heading background images on .simplelayout
italia/developers.italia.it pull request #715
Opened 2020-09-25 15:49 UTC by Laischon

## Description
As already mentioned in # 699, this PR corrects the display of the images present at the beginning of the "Simplelayout".

Such as?
Added a `div` that contains a background image, i.e. the header image. This `div` has replaced the `img` tag previously present and has a minimum height of 405px and is responsive on width.

**Before:** ![image_before_1](https://user-images.githubusercontent.com/7593569/94287956-31257f00-ff57-11ea-9354-012077e2bd1f.PNG)

**After:** 
![image_after_1](https://user-images.githubusercontent.com/7593569/94288069-4b5f5d00-ff57-11ea-8f5e-c303f949469b.PNG)

## Checklist

- [ x ] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ x ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ x ] Have you written new tests for your core changes, as applicable?
- [ x ] Have you successfully ran tests with your changes locally?
- [ x ] Ready for review! :rocket:

## Fixes

- Fixes #699

2020-09-25 16:16 UTC, bfabio commented on assets/scss/main.scss
> +          margin: 0 15%;
```suggestion
            margin: 0 15%;
```

2020-09-25 16:22 UTC, bfabio requested changes
This doesn't cover the whole viewport at my resolution:

![image](https://user-images.githubusercontent.com/788293/94291369-d4789300-ff5b-11ea-8f70-ec0f3fa785d5.png)

whereas before it did:

![image](https://user-images.githubusercontent.com/788293/94291524-0a1d7c00-ff5c-11ea-86c4-37362e95ba81.png)

is this on purpose?

2020-09-25 17:40 UTC, Laischon reviewed
Changed media rule for images on viewport with a width lower than 1600px

2020-09-28 09:47 UTC, bfabio approved these changes

2020-09-28 12:50 UTC, sebbalex approved these changes

2020-09-28 13:00 UTC, merged

2020-09-28 13:01 UTC, bfabio commented
@Laischon Thanks, merged! :rocket: