#491 issue of the tagline getting highlighted solved.
italia/developers.italia.it pull request #765
Opened 2020-10-09 10:16 UTC by namrataaaa

Checklist
- [ x ] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ x ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ x ] Have you written new tests for your core changes, as applicable?
- [ x ] Have you successfully ran tests with your changes locally?
- [ x ] Ready for review! :rocket:

2020-10-09 11:01 UTC, bfabio commented
@namrataaaa Thanks for the PR :+1: Can you please rebase it on master?

2020-10-09 19:49 UTC, namrataaaa commented
> @namrataaaa Thanks for the PR 👍 Can you please rebase it on master?

I rebased it on master. Please have a look and let me know if I need to make any more changes.

2020-10-12 17:30 UTC, bfabio requested changes

2020-10-12 17:30 UTC, bfabio commented on _includes/header.html
> +                endif %>
```suggestion
                endif %}
```

2020-10-13 05:38 UTC, namrataaaa commented
Hi, @bfabio I made the changes as requested. Please have a look and let me know if everything is okay.

2020-10-13 06:22 UTC, bfabio requested changes
Hi @namrataaaa, there's something wrong with the header, you can see the preview here: https://deploy-preview-765--developers-italia.netlify.app/

2020-10-13 09:38 UTC, namrataaaa commented
@bfabio I apologize for my mistake. It has now been fixed. Have a look please.

2020-10-13 11:37 UTC, bfabio requested changes
Almost there :wink:

2020-10-13 11:37 UTC, bfabio commented on assets/scss/main.scss
> +
```suggestion
```

2020-10-13 11:37 UTC, bfabio commented on assets/scss/main.scss
> +                color: #fff;
Let's use 4 spaces for indentation.

2020-10-13 11:37 UTC, bfabio commented on assets/scss/main.scss
>              }
```suggestion
        }
```

2020-10-13 16:54 UTC, bfabio commented on assets/scss/main.scss
> +                color: #fff;
@namrataaaa  `.Header-subtitle`'s rules are still 8 spaces indented.

2020-10-13 17:56 UTC, bfabio approved these changes

2020-10-13 17:59 UTC, merged

2020-10-13 18:00 UTC, bfabio commented
@namrataaaa Thanks for your work, merged :rocket:

2020-10-13 18:13 UTC, namrataaaa commented
> @namrataaaa Thanks for your work, merged 🚀

Thank you too. I learnt a lot and had a great experience. 😄